In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import confusion_matrix, classification_report

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [3]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
df = pd.read_csv('Resources/lending_data.csv')

# Review the DataFrame
df.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [18]:
# Separate the data into labels and features

# Separate the y variable, the labels
y = df.loan_status

# Separate the X variable, the features
X = df.drop('loan_status', axis=1)

In [19]:
# Review the y variable Series - y.head 
 y.head

<bound method NDFrame.head of 0        0
1        0
2        0
3        0
4        0
        ..
77531    1
77532    1
77533    1
77534    1
77535    1
Name: loan_status, Length: 77536, dtype: int64>

In [20]:
# Review the X variable DataFrame -- will use x.head
x.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  
0                 1       22800  
1                 0       13600  
2                 0       16100  
3                 1       22700  
4                 1       23000

In [28]:
#this is to separate out the training data from the testing data -- step 1 
len(X_train)/len(X)

0.75

In [29]:
#this is to separate out the training data from the testing data -- step 2
len(X_test)/len(X)

0.25

### Step 3: Split the data into training and testing datasets by using `train_test_split`.

In [21]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)


---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [34]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
clf = LogisticRegression(random_state=1)

# Fit the model using training data
# Explnation: clf.fit(X_train, y_train) is training the model clf on the input features X_train and the target variable y_train. 
clf.fit(X_train, y_train)

LogisticRegression(random_state=1)

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [36]:
# Make a prediction using the testing data
y_test

60914    0
36843    0
1966     0
70137    0
27237    0
        ..
45639    0
11301    0
51614    0
4598     0
2793     0
Name: loan_status, Length: 19384, dtype: int64

In [37]:
# Make a prediction using the testing data
clf.predict(X_test)


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [39]:
# Make a prediction using the testing data
pred = clf.predict(X_test)

### Step 3: Evaluate the model’s performance by doing the following:

* Generate a confusion matrix.

* Print the classification report.

In [42]:
# Generate a confusion matrix for the model
confusion_matrix(y_test, pred)

array([[18663,   102],
       [   56,   563]], dtype=int64)

In [43]:
# Generate a confusion matrix for the model
print(confusion_matrix(y_test, pred))

[[18663   102]
 [   56   563]]


In [44]:
# Print the classification report for the model
classification_report(y_test, pred)

'              precision    recall  f1-score   support\n\n           0       1.00      0.99      1.00     18765\n           1       0.85      0.91      0.88       619\n\n    accuracy                           0.99     19384\n   macro avg       0.92      0.95      0.94     19384\nweighted avg       0.99      0.99      0.99     19384\n'

In [45]:
# Print the classification report for the model
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18765
           1       0.85      0.91      0.88       619

    accuracy                           0.99     19384
   macro avg       0.92      0.95      0.94     19384
weighted avg       0.99      0.99      0.99     19384



In [47]:
len(df[df.loan_status==0])

75036

In [48]:
y.value_counts()

loan_status
0    75036
1     2500
Name: count, dtype: int64

In [58]:
df + pd.concat([df[df.loan_status==0][:2500],df[df.loan_status==1]])

loan_size  interest_rate  borrower_income  debt_to_income  \
0        21400.0         15.344         105600.0        0.863636   
1        16800.0         13.384          87200.0        0.623853   
2        18000.0         13.926          92200.0        0.698482   
3        21400.0         15.328         105400.0        0.861480   
4        21600.0         15.396         106000.0        0.867925   
...          ...            ...              ...             ...   
77531    38200.0         22.522         173200.0        1.307159   
77532    35400.0         21.324         161800.0        1.258344   
77533    35200.0         21.190         160600.0        1.252802   
77534    32600.0         20.136         150600.0        1.203187   
77535    31200.0         19.484         144600.0        1.170124   

       num_of_accounts  derogatory_marks  total_debt  loan_status  
0                 10.0               2.0     45600.0          0.0  
1                  6.0               0.0     27200.0          0.0  
2                  6.0               0.0     32200.0          0.0  
3                 10.0               2.0     45400.0          0.0  
4                 10.0               2.0     46000.0          0.0  
...                ...               ...         ...          ...  
77531             24.0               4.0    113200.0          2.0  
77532             22.0               4.0    101800.0          2.0  
77533             22.0               4.0    100600.0          2.0  
77534             20.0               4.0     90600.0          2.0  
77535             18.0               4.0     84600.0          2.0  

[77536 rows x 8 columns]

### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** See below

In [ ]:
Overview of the Analysis
In this analysis, we aimed to evaluate the performance of a logistic regression model in predicting loan statuses. Specifically, the objective was to determine whether a loan is healthy (0) or high-risk (1). The financial data used in this analysis included features related to loan applications, such as applicant income, loan amount, credit history, etc. The target variable was the loan status, which we needed to predict.

The stages of the machine learning process included:

Data preprocessing: Cleaning and preparing the data for analysis.
Feature selection: Identifying the most relevant features for the model.
Model training: Using the logistic regression algorithm to train the model on the training data.
Model evaluation: Assessing the model's performance using the test data and generating a classification report.

** Results ** 
Logistic Regression Model:
 Class 0 (Healthy Loan):
       Precision: 1.00
       Recall: 0.99
       F1-Score: 1.00
       Support: 18,765
 Class 1 (High-Risk Loan):
       Precision: 0.85
       Recall: 0.91
       F1-Score: 0.88
       Support: 619
 Overall Metrics:
       Accuracy: 0.99
       Macro Average:
         Precision: 0.92
         Recall: 0.95
         F1-Score: 0.94
 Weighted Average:
       Precision: 0.99
       Recall: 0.99
       F1-Score: 0.99


** Summary ** 
The logistic regression model performs exceptionally well in predicting healthy loans, with perfect precision, recall, and F1-score for Class 0. The model also performs well in predicting high-risk loans, though slightly less effectively, with a precision of 0.85, recall of 0.91, and F1-score of 0.88. The overall accuracy of the model is very high at 99%, indicating reliable performance.
       The logistic regression model seems to perform best overall, especially in predicting healthy loans.
       Performance does depend on the problem we are trying to solve. If predicting high-risk loans (1s) is more critical, the slightly lower precision and recall for Class 1 should be considered. However, given the high overall accuracy and balanced performance metrics, this model is recommended for predicting loan statuses in this scenario.

If I was a conservative bank that did not lend on subpar loans, then I would use this model and only approve loans that met the healthly loan profile (as long as it met fair lending requirements and other applicable government regulations). 



---